# Generated by Django 5.2.7 on 2025-11-02 07:40

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('programming', 'Programming'), ('data_structures', 'Data Structures'), ('algorithms', 'Algorithms'), ('databases', 'Databases'), ('web_development', 'Web Development'), ('mobile_development', 'Mobile Development'), ('machine_learning', 'Machine Learning'), ('cloud_computing', 'Cloud Computing'), ('devops', 'DevOps'), ('cybersecurity', 'Cybersecurity'), ('general', 'General Knowledge')], default='general', max_length=50)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard'), ('expert', 'Expert')], default='medium', max_length=20)),
                ('duration_minutes', models.IntegerField(help_text='Exam duration in minutes', validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(300)])),
                ('total_marks', models.IntegerField(default=100, validators=[django.core.validators.MinValueValidator(1)])),
                ('passing_marks', models.IntegerField(default=40, validators=[django.core.validators.MinValueValidator(0)])),
                ('is_published', models.BooleanField(default=False)),
                ('is_premium', models.BooleanField(default=False)),
                ('allow_review', models.BooleanField(default=True, help_text='Allow users to review answers after submission')),
                ('randomize_questions', models.BooleanField(default=False)),
                ('show_results_immediately', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_attempts', models.IntegerField(default=0)),
                ('average_score', models.FloatField(default=0.0)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_exams', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'exams',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExamAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('completed', 'Completed'), ('abandoned', 'Abandoned')], default='in_progress', max_length=20)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('time_taken_minutes', models.IntegerField(blank=True, null=True)),
                ('score', models.FloatField(default=0.0)),
                ('percentage', models.FloatField(default=0.0)),
                ('marks_obtained', models.FloatField(default=0.0)),
                ('total_marks', models.FloatField(default=0.0)),
                ('is_passed', models.BooleanField(default=False)),
                ('is_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='exams.exam')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'exam_attempts',
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('question_type', models.CharField(choices=[('mcq', 'Multiple Choice (Single Answer)'), ('multiple', 'Multiple Choice (Multiple Answers)'), ('true_false', 'True/False'), ('short_answer', 'Short Answer'), ('code', 'Code')], default='mcq', max_length=20)),
                ('options', models.JSONField(blank=True, default=list)),
                ('correct_answer', models.JSONField(default=list)),
                ('marks', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('negative_marks', models.FloatField(default=0, help_text='Marks to deduct for wrong answer', validators=[django.core.validators.MinValueValidator(0)])),
                ('explanation', models.TextField(blank=True, help_text='Explanation shown after answering')),
                ('order', models.IntegerField(default=0, help_text='Question order in exam')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='exams.exam')),
            ],
            options={
                'db_table': 'questions',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_answer', models.JSONField(blank=True, null=True)),
                ('is_correct', models.BooleanField(default=False)),
                ('marks_awarded', models.FloatField(default=0.0)),
                ('time_spent_seconds', models.IntegerField(default=0, help_text='Time spent on this question')),
                ('answered_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='exams.examattempt')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='exams.question')),
            ],
            options={
                'db_table': 'answers',
            },
        ),
        migrations.AddIndex(
            model_name='exam',
            index=models.Index(fields=['category', 'difficulty'], name='exams_categor_ca24b3_idx'),
        ),
        migrations.AddIndex(
            model_name='exam',
            index=models.Index(fields=['is_published'], name='exams_is_publ_8bb3b8_idx'),
        ),
        migrations.AddIndex(
            model_name='examattempt',
            index=models.Index(fields=['user', 'exam'], name='exam_attemp_user_id_a9e9b6_idx'),
        ),
        migrations.AddIndex(
            model_name='examattempt',
            index=models.Index(fields=['status'], name='exam_attemp_status_db025a_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['exam', 'order'], name='questions_exam_id_6a4fc8_idx'),
        ),
        migrations.AddIndex(
            model_name='answer',
            index=models.Index(fields=['attempt', 'question'], name='answers_attempt_2fb0d3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='answer',
            unique_together={('attempt', 'question')},
        ),
    ]
