# Generated by Django 5.2.7 on 2025-11-02 09:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_exams_taken', models.IntegerField(default=0)),
                ('total_exams_passed', models.IntegerField(default=0)),
                ('average_exam_score', models.FloatField(default=0.0)),
                ('highest_exam_score', models.FloatField(default=0.0)),
                ('total_exam_time_minutes', models.IntegerField(default=0)),
                ('total_interviews_taken', models.IntegerField(default=0)),
                ('total_interviews_completed', models.IntegerField(default=0)),
                ('average_interview_score', models.FloatField(default=0.0)),
                ('highest_interview_score', models.FloatField(default=0.0)),
                ('total_interview_time_minutes', models.IntegerField(default=0)),
                ('total_questions_answered', models.IntegerField(default=0)),
                ('total_correct_answers', models.IntegerField(default=0)),
                ('current_streak_days', models.IntegerField(default=0)),
                ('longest_streak_days', models.IntegerField(default=0)),
                ('last_activity_date', models.DateField(blank=True, null=True)),
                ('skill_scores', models.JSONField(blank=True, default=dict)),
                ('weak_areas', models.JSONField(blank=True, default=list)),
                ('strong_areas', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Analytics',
                'verbose_name_plural': 'User Analytics',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('exam_started', 'Exam Started'), ('exam_completed', 'Exam Completed'), ('interview_started', 'Interview Started'), ('interview_completed', 'Interview Completed'), ('login', 'User Login')], max_length=50)),
                ('description', models.TextField(blank=True)),
                ('exam_attempt_id', models.IntegerField(blank=True, null=True)),
                ('interview_id', models.IntegerField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'activity_type'], name='analytics_a_user_id_3c5a5d_idx'), models.Index(fields=['user', 'created_at'], name='analytics_a_user_id_1fe5d2_idx')],
            },
        ),
        migrations.CreateModel(
            name='PerformanceTrend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_type', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], max_length=20)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('exams_taken', models.IntegerField(default=0)),
                ('exams_passed', models.IntegerField(default=0)),
                ('average_exam_score', models.FloatField(default=0.0)),
                ('interviews_taken', models.IntegerField(default=0)),
                ('interviews_completed', models.IntegerField(default=0)),
                ('average_interview_score', models.FloatField(default=0.0)),
                ('total_time_spent_minutes', models.IntegerField(default=0)),
                ('questions_answered', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_trends', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-period_start'],
                'indexes': [models.Index(fields=['user', 'period_type', 'period_start'], name='analytics_p_user_id_87d619_idx')],
                'unique_together': {('user', 'period_type', 'period_start')},
            },
        ),
    ]
