# Generated by Django 5.2.7 on 2025-11-02 08:08

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('interview_type', models.CharField(choices=[('technical', 'Technical'), ('behavioral', 'Behavioral'), ('system_design', 'System Design'), ('coding', 'Coding'), ('hr', 'HR')], max_length=50)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=20)),
                ('job_role', models.CharField(max_length=200)),
                ('company_name', models.CharField(blank=True, max_length=200)),
                ('job_description', models.TextField(blank=True)),
                ('required_skills', models.JSONField(default=list)),
                ('duration_minutes', models.IntegerField(default=30)),
                ('total_questions', models.IntegerField(default=5)),
                ('use_ai', models.BooleanField(default=True)),
                ('enable_video', models.BooleanField(default=False)),
                ('enable_audio', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('total_score', models.FloatField(default=0.0)),
                ('max_score', models.FloatField(default=100.0)),
                ('percentage', models.FloatField(default=0.0)),
                ('overall_feedback', models.TextField(blank=True)),
                ('strengths', models.JSONField(default=list)),
                ('weaknesses', models.JSONField(default=list)),
                ('recommendations', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'interviews',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InterviewQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('question_type', models.CharField(choices=[('technical', 'Technical'), ('behavioral', 'Behavioral'), ('coding', 'Coding'), ('system_design', 'System Design'), ('general', 'General')], max_length=50)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], max_length=20)),
                ('expected_duration_minutes', models.IntegerField(default=5)),
                ('expected_answer', models.TextField(blank=True)),
                ('evaluation_criteria', models.JSONField(default=list)),
                ('order', models.IntegerField(default=0)),
                ('is_ai_generated', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('interview', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='interview.interview')),
            ],
            options={
                'db_table': 'interview_questions',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='InterviewResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_response', models.TextField(blank=True)),
                ('audio_url', models.URLField(blank=True, max_length=500)),
                ('video_url', models.URLField(blank=True, max_length=500)),
                ('code_response', models.TextField(blank=True)),
                ('time_taken_seconds', models.IntegerField(default=0)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('score', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)])),
                ('ai_feedback', models.TextField(blank=True)),
                ('evaluation_metrics', models.JSONField(default=dict)),
                ('is_evaluated', models.BooleanField(default=False)),
                ('needs_review', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('interview', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='interview.interview')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='interview.interviewquestion')),
            ],
            options={
                'db_table': 'interview_responses',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='InterviewTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('interview_type', models.CharField(choices=[('technical', 'Technical'), ('behavioral', 'Behavioral'), ('system_design', 'System Design'), ('coding', 'Coding'), ('hr', 'HR')], max_length=50)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], max_length=20)),
                ('duration_minutes', models.IntegerField(default=30)),
                ('questions', models.JSONField(default=list)),
                ('times_used', models.IntegerField(default=0)),
                ('average_score', models.FloatField(default=0.0)),
                ('is_active', models.BooleanField(default=True)),
                ('is_premium', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interview_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'interview_templates',
                'ordering': ['-times_used', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='interview',
            index=models.Index(fields=['user', 'status'], name='interviews_user_id_2db33c_idx'),
        ),
        migrations.AddIndex(
            model_name='interview',
            index=models.Index(fields=['interview_type'], name='interviews_intervi_328b69_idx'),
        ),
        migrations.AddIndex(
            model_name='interview',
            index=models.Index(fields=['created_at'], name='interviews_created_a62a66_idx'),
        ),
        migrations.AddIndex(
            model_name='interviewquestion',
            index=models.Index(fields=['interview', 'order'], name='interview_q_intervi_5c5500_idx'),
        ),
        migrations.AddIndex(
            model_name='interviewresponse',
            index=models.Index(fields=['interview', 'question'], name='interview_r_intervi_da6a81_idx'),
        ),
    ]
